services:
  postgres:
    image: postgres:15.6-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mealprepinator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .  # Der Pfad zum Dockerfile für deine Anwendung
      dockerfile: Dockerfile
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mealprepinator
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
